apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec: 
      containers:
        - name: goserver
          image: jamilsonmelo/goserver
          env: 
            - name: USER
              value: "postgres"
            - name: HOST
              value: "localhost"
            - name: PORT
              value: "5432"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
