apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec: 
      containers:
        - name: goserver
          image: jamilsonmelo/goserver
          #envFrom: // load configmap file with all environment variables
            #- configMapKeyRef:
              #name: goserver-env
          env: 
            - name: USER
              valueFrom:
                configMapKeyRef: 
                  name: "goserver-env"
                  key: USER
            - name: HOST
              valueFrom:
                configMapKeyRef: 
                  name: "goserver-env"
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef: 
                  name: "goserver-env"
                  key: PORT
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
